# Generated by Django 5.0.2 on 2025-06-06 10:21

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DistrictObligation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('district_name', models.CharField(max_length=100)),
                ('current_figure', models.DecimalField(decimal_places=2, max_digits=10)),
                ('balance', models.DecimalField(decimal_places=2, max_digits=10)),
                ('projected_target', models.DecimalField(decimal_places=2, max_digits=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'District Obligation',
                'verbose_name_plural': 'District Obligations',
                'ordering': ['district_name'],
            },
        ),
        migrations.CreateModel(
            name='ZonalObligation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(choices=[('chadzoka', 'Chadzoka (National Project)'), ('national_account', 'National Account'), ('zonal_seminar', 'Zonal Seminar'), ('nyc', 'National Youth Conference (NYC)'), ('weddings', 'Weddings'), ('provincial_project', 'Provincial Project'), ('zonal_admin', 'Zonal Admin'), ('national_donation', 'National Donation'), ('directors_gift', "Director's Gift"), ('hd', 'HD'), ('secretaries_seminar', 'Secretaries and Advisors Seminar'), ('advisors_conference', 'Advisors Conference')], max_length=50)),
                ('current_figure', models.DecimalField(decimal_places=2, max_digits=10)),
                ('balance', models.DecimalField(decimal_places=2, max_digits=10)),
                ('projected_target', models.DecimalField(decimal_places=2, max_digits=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Zonal Obligation',
                'verbose_name_plural': 'Zonal Obligations',
                'ordering': ['category'],
            },
        ),
    ]
