# Generated by Django 5.0.2 on 2025-06-06 10:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('obligations', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='districtobligation',
            name='balance',
        ),
        migrations.RemoveField(
            model_name='zonalobligation',
            name='balance',
        ),
        migrations.AlterField(
            model_name='districtobligation',
            name='current_figure',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='districtobligation',
            name='district_name',
            field=models.CharField(max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='districtobligation',
            name='projected_target',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='zonalobligation',
            name='category',
            field=models.CharField(choices=[('chadzoka', 'Chadzoka (National Project)'), ('national_account', 'National Account'), ('zonal_seminar', 'Zonal Seminar'), ('nyc', 'National Youth Conference (NYC)'), ('weddings', 'Weddings'), ('provincial_project', 'Provincial Project'), ('zonal_admin', 'Zonal Admin'), ('national_donation', 'National Donation'), ('directors_gift', "Director's Gift"), ('hd', 'HD'), ('secretaries_seminar', 'Secretaries and Advisors Seminar'), ('advisors_conference', 'Advisors Conference')], max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name='zonalobligation',
            name='current_figure',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='zonalobligation',
            name='projected_target',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
